server.port=8082
spring.application.name=order-service
spring.data.mongodb.uri=mongodb://localhost:27017/orderdb
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

grpc.client.client-service.address=static://localhost:9091
grpc.client.client-service.negotiationType=plaintext
