spring.data.mongodb.uri=${MONGODB_URI:mongodb://mongodb:27017/orderdb}
grpc.client.client-service.address=${CLIENT_SERVICE_GRPC_ADDRESS:static://client-service:9091}
grpc.client.client-service.negotiationType=plaintext
