server.port=8081
spring.application.name=client-service
spring.data.mongodb.uri=mongodb://localhost:27017/clientdb
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

grpc.server.port=9091

jwt.secret=9a4f2c8d3b7a1e5f8g9h0i1j2k3l4m5n6o7p8q9r0s1t2u3v4w5x6y7z8a9b0c1d
